# Generated by Django 5.0.6 on 2024-07-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbs", "0004_post_writer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="likeforcomment",
            old_name="target",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="likeforpost",
            old_name="target",
            new_name="post",
        ),
        migrations.RemoveField(
            model_name="likeforcomment",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="likeforpost",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="likeforcomment",
            name="user",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="likeforpost",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
