# Generated by Django 5.0.6 on 2024-08-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bbs", "0005_rename_target_likeforcomment_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="photos/"),
            preserve_default=False,
        ),
    ]
